### ISSUE TITLE
k8s.io/kubelet/pkg/apis/deviceplugin/v1beta1: cannot compile Go 1.22 code

### ISSUE THREAD

**Issue by nkartem** [aws/aws-nitro-enclaves-k8s-device-plugin#14]
1. I have EKS v1.29 and one worker node with the function "Nitro Enclaves". When I run the command `./scripts/build.sh` I have an error

`Step 7/10 : RUN CGO_ENABLED=0 go build -a -ldflags='-s -w -extldflags="-static"' .
 ---> Running in eb24d5a92f02
k8s.io/kubelet/pkg/apis/deviceplugin/v1beta1: cannot compile Go 1.22 code
The command '/bin/sh -c CGO_ENABLED=0 go build -a -ldflags='-s -w -extldflags="-static"' .' returned a non-zero code: 1`

2. Chande dockerfile where install  GO v1.19. 

```
`# Copyright 2022 Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-3.0

# Build the device plugin from sources

FROM amazonlinux:2 as builder

# Install dependencies
RUN yum install -y wget tar gzip

# Download and install Go 1.19
RUN wget https://go.dev/dl/go1.19.linux-amd64.tar.gz
RUN tar -C /usr/local -xzf go1.19.linux-amd64.tar.gz

# Set Go environment variables
ENV PATH=$PATH:/usr/local/go/bin
ENV GOPATH=/go
ENV PATH=$GOPATH/bin:$PATH

WORKDIR build_dir/
COPY *.go ./
COPY go.sum ./

RUN go mod init k8s-ne-device-plugin && \
    go mod tidy && \
    go mod vendor

RUN CGO_ENABLED=0 go build -a -ldflags='-s -w -extldflags="-static"' .

# Create a bare minumum image that only contains the device plugin binary.

FROM scratch as device_plugin

COPY --from=builder /build_dir/k8s-ne-device-plugin /usr/bin/k8s-ne-device-plugin

CMD ["/usr/bin/k8s-ne-device-plugin","-logtostderr=true","-v=0"]`
```

After that, I get the Docker image:
```
docker images
REPOSITORY                             TAG          IMAGE ID       CREATED          SIZE
aws-nitro-enclaves-k8s-device-plugin   0.1-x86_64   80c0010ef8bf   22 seconds ago   9.66MB
ne-k8s-device-plugin-build             latest       8787e57c058d   24 seconds ago   1.44GB
amazonlinux                            2            e76800ed324e   2 weeks ago      165MB
```

But this image does not run in EKS

`Back-off restarting failed container aws-nitro-enclaves-k8s-dp in pod aws-nitro-enclaves-k8s-daemonset-8lb8v_kube-system`

3. My manifest file of k8s. Change only parameter IMAGES to my ECR

```
apiVersion: v1
kind: Namespace
metadata:
  name: nitro-enclaves
  labels:
    name: nitro-enclaves
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: aws-nitro-enclaves-k8s-daemonset
  namespace: kube-system
  labels:
    name: aws-nitro-enclaves-k8s-dp
    role: agent
spec:
  selector:
    matchLabels:
      name: aws-nitro-enclaves-k8s-dp
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: aws-nitro-enclaves-k8s-dp
      annotations:
        node.kubernetes.io/bootstrap-checkpoint: "true"
    spec:
      nodeSelector:
        aws-nitro-enclaves-k8s-dp: enabled
      priorityClassName: "system-node-critical"
      hostname: aws-nitro-enclaves-k8s-dp
      containers:
      - name: aws-nitro-enclaves-k8s-dp
        image: 123456789012.dkr.ecr.us-west-1.amazonaws.com/enclave:1
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
        resources:
          limits:
            cpu: 100m
            memory: 15Mi
          requests:
            cpu: 10m
            memory: 15Mi
        volumeMounts:
          - name: device-plugin
            mountPath: /var/lib/kubelet/device-plugins
          - name: dev-dir
            mountPath: /dev
          - name: sys-dir
            mountPath: /sys
      volumes:
        - name: device-plugin
          hostPath:
            path: /var/lib/kubelet/device-plugins
        - name: dev-dir
          hostPath:
            path: /dev
        - name: sys-dir
          hostPath:
            path: /sys
      terminationGracePeriodSeconds: 30
```
