### ISSUE TITLE
[Question] - Increase the nitro_enclaves capacity

### ISSUE THREAD

**Issue by kbatista-nu** [aws/aws-nitro-enclaves-k8s-device-plugin#7]
I'm testing the EKS using Enclave Nitro and I'm not getting any progress

When I apply the plugin it adds in the node's Capacity the value`aws.ec2.nitro/nitro_enclaves: "1"`
> This way it is possible to use only 1 pod with nitro enclave in each node.

Is it possible to increase this value? How can I do this?

**Comment by kbatista-nu** [comment]
When I try to run my deployment with more than 1 enclave, I get an error

### Deployment
```
....
        resources:
          limits:
            aws.ec2.nitro/nitro_enclaves: "4"
            hugepages-1Gi: 1Gi
            cpu: 2
          requests:
            aws.ec2.nitro/nitro_enclaves: "4"
            hugepages-1Gi: 1Gi
```

### Node

```
Capacity:
  attachable-volumes-aws-ebs:    25
  aws.ec2.nitro/nitro_enclaves:  0
  cpu:                           4
  ephemeral-storage:             20959212Ki
  hugepages-1Gi:                 4Gi
  hugepages-2Mi:                 0
  memory:                        32408692Ki
  pods:                          58
Allocatable:
  attachable-volumes-aws-ebs:    25
  aws.ec2.nitro/nitro_enclaves:  0
  cpu:                           3920m
  ephemeral-storage:             18242267924
  hugepages-1Gi:                 4Gi
  hugepages-2Mi:                 0
  memory:                        27197556Ki
  pods:                          58
```


### Error
```
Warning  FailedScheduling  27s   default-scheduler  0/1 nodes are available: 1 Insufficient aws.ec2.nitro/nitro_enclaves. preemption: 0/1 nodes are available: 1 No preemption victims found for incoming pod.
```
